web:
  image: tomcat:9.0.10-jre10
  volumes:
    - ./docker-files/context.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml
    - ./docker-files/context.xml:/usr/local/tomcat/webapps/host-manager/META-INF/context.xml
    - ./docker-files/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
    - ./target/onepay-sdk-example.war:/usr/local/tomcat/webapps/onepay-sdk-example.war
  ports:
    - "8081:8080"
  environment:
    - HOST_IP=CAMBIA_POR_TU_UP